'use client';

import './globals.css'
import { Inter } from 'next/font/google'
// import { UserProvider } from '@auth0/nextjs-auth0/client';
import { Auth0Provider } from '@auth0/auth0-react';
import {
  QueryClient,
  QueryClientProvider,
} from 'react-query'

const queryClient = new QueryClient()

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Auth0Provider
      domain={process.env.NEXT_PUBLIC_AUTH0_DOMAIN || ''}
      clientId={process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID || ''}
      authorizationParams={{
        redirect_uri: typeof window !== "undefined" ? window.location.origin : "",
        audience: process.env.NEXT_PUBLIC_AUTH0_AUDIENCE,
        scope: "read:current_user update:current_user_metadata"  
      }}
    >
      <QueryClientProvider client={queryClient}>

        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </QueryClientProvider>

    </Auth0Provider>
  )
}
